sudo: true
language: nix

notifications:
  email: false

os:
  - linux
  - osx

cache:
  directories:
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

env:
  global:
    - GITHUB_RELEASE_VERSION=1.2.4

install:
  - nix run -c stack setup --no-terminal
  - nix run -c stack build --only-dependencies --test

script:
  - nix run -c stack test
