# Changed the name here because nixpkgs also includes a vaultenv and we haven't
# figured out how to mask that when we build vaultenv with nix itself.
name: vaultenv-real
version: 0.13.1
synopsis: Runs processes with secrets from HashiCorp Vault
license: BSD3
github: channable/vaultenv

dependencies:
  - aeson
  - base
  - async
  - bytestring
  - connection
  - containers
  - dotenv
  - directory
  - http-conduit
  - http-client
  - megaparsec
  - optparse-applicative
  - parser-combinators
  - retry
  - text
  - unordered-containers
  - unix
  - utf8-string
  - optparse-applicative

ghc-options: -Wall -Werror

library:
  source-dirs: src

executables:
  vaultenv:
    main: Main.hs
    source-dirs: app
    dependencies:
      - vaultenv-real

tests:
  vaultenv-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vaultenv-real
    - hspec
    - hspec-discover
    - hspec-expectations
    - directory
    - QuickCheck
