# Also take care to update the compiler in default.nix to the
# compiler used in this Stackage snapshot.
# This value has a companion file named `stack-static-build.yaml`, used for static builds.
# When updating this resolver, update that file as well.
resolver: ghc-8.6.5

packages:
  - "."

# This makes stack pick up our nix environment for building by default.
nix:
  enable: true
  shell-file: nix/stack-shell.nix
  path: ["nixpkgs=./nix/nixpkgs-pinned.nix"]
